language: c

cache:
  directories:
  - $HOME/.stack

# The different configurations we want to test.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
matrix:
  include:
  - env: ARGS="--stack-yaml stack-7.10.yaml"
    compiler: ": #stack 7.10.3"
    addons: { apt: { packages: [ghc-7.10.3], sources: [hvr-ghc] } }

  - env: ARGS="--stack-yaml stack-8.0.yaml"
    compiler: ": #stack 8.0.1"
    addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }

  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: { apt: { packages: [libgmp,libgmp-dev] } }

  allow_failures:
  # Nightly builds are allowed to fail
  - env: ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps --ghc-options=-Werror
